### ISSUE TITLE
the setup script does not work with python 3.10

### ISSUE THREAD

**Issue by jkotan** [nexdatas/tools#286]
I get
```
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 188, in write_pkg_file
    license = rfc822_escape(self.get_license())
  File "/usr/lib/python3.10/distutils/util.py", line 479, in rfc822_escape
    lines = header.split('\n')
AttributeError: 'tuple' object has no attribute 'split'
```
when I run `setup.py install` on ubuntu jammy
